name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install dvc[all]  # Ensure all DVC dependencies are installed
          pip install --upgrade cryptography  # Update cryptography library
          pip install -r requirements.txt

      - name: Set up Google Drive credentials
        run: |
          mkdir -p /home/runner/.config/dvc
          echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}' | base64 -d > /home/runner/.config/dvc/gdrive-credentials.json
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}

      - name: modify dvc to use drive service account
        run: |
          dvc remote modify myremote gdrive_use_service_account true

      - name: add the service account json file to the dvc remote config
        run: |
          dvc remote modify myremote gdrive_service_account_json_file_path /home/runner/.config/dvc/gdrive-credentials.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.user_name }}
          password: ${{ secrets.password }}

      - name: Build Docker image
        run: |
          docker build -t tinsu2/tellco:latest .

      - name: Push Docker image
        run: |
          docker push tinsu2/tellco:latest
